# Generated by Django 2.0 on 2019-04-25 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeQuote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('emai', models.EmailField(max_length=200)),
                ('cell_number', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('service_req', models.CharField(choices=[('nw', 'New Pavement Installation'), ('cp', 'Cleaning pavements'), ('pm', 'Pavement Maintenance'), ('tc', 'Tiles cleaning'), ('tm', 'Tiles Maintenance'), ('nt', 'New Tiles Installation'), ('oe', 'Other services')], max_length=4)),
                ('additional_info', models.TextField()),
                ('loc_from', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Newletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
    ]
