# Generated by Django 2.0 on 2019-04-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190426_0327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freequote',
            old_name='first_name',
            new_name='name',
        ),
    ]
