# Generated by Django 2.0 on 2019-04-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190426_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freequote',
            old_name='emai',
            new_name='email',
        ),
    ]
