# Generated by Django 2.0 on 2019-04-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190426_0645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freequote',
            old_name='loc_from',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='freequote',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='freequote',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='freequote',
            name='cell_number',
            field=models.IntegerField(blank=True),
        ),
    ]
